extend type Mutation {
  """
  ✨ Insert a single `DeviceEvent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deviceEvent_insert(
    """
    Data object to insert into the table.
    """
    data: DeviceEvent_Data!
  ): DeviceEvent_KeyOutput! @fdc_generated(from: "DeviceEvent", purpose: INSERT_SINGLE)
  """
  ✨ Insert `DeviceEvent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deviceEvent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DeviceEvent_Data!]!
  ): [DeviceEvent_KeyOutput!]! @fdc_generated(from: "DeviceEvent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `DeviceEvent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeviceEvent`.
  """
  deviceEvent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DeviceEvent_Data!
  ): DeviceEvent_KeyOutput! @fdc_generated(from: "DeviceEvent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `DeviceEvent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeviceEvent`.
  """
  deviceEvent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DeviceEvent_Data!]!
  ): [DeviceEvent_KeyOutput!]! @fdc_generated(from: "DeviceEvent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `DeviceEvent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DeviceEvent` or `null` if not found.
  """
  deviceEvent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeviceEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeviceEvent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DeviceEvent_Data!
  ): DeviceEvent_KeyOutput @fdc_generated(from: "DeviceEvent", purpose: UPDATE_SINGLE)
  """
  ✨ Update `DeviceEvent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  deviceEvent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DeviceEvent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DeviceEvent_Data!
  ): Int! @fdc_generated(from: "DeviceEvent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `DeviceEvent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  deviceEvent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeviceEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeviceEvent_FirstRow
  ): DeviceEvent_KeyOutput @fdc_generated(from: "DeviceEvent", purpose: DELETE_SINGLE)
  """
  ✨ Delete `DeviceEvent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  deviceEvent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DeviceEvent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DeviceEvent", purpose: DELETE_MULTIPLE)
}
